In [2]:
#1. What is 7 to the power of 
print(7**4)

2401


In [3]:
#2. Split this string:
s = "Hi there Sam!"
s.split()

['Hi', 'there', 'Sam!']

In [4]:
#3. Given the variables: planet = "Earth" diameter = 1274 Use .format() to print the following string:  The diameter of Earth is 12742 kilometers.
planet = "Earth"
diameter = 12742
print("The diameter of {p} is {d} kilometers".format(p=planet,d=diameter))

The diameter of Earth is 12742 kilometers


In [5]:
# 4. Given this nested list, use indexing to grab the word "hello” lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

In [6]:
lst[3]

[5, [100, 200, ['hello']], 23, 11]

In [7]:
lst[3][1]

[100, 200, ['hello']]

In [8]:
lst[3][1][2]

['hello']

In [9]:
lst[3][1][2][0]

'hello'

In [10]:
#5. Given this nested dictionary grab the word "hello". d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d)


{'k1': [1, 2, 3, {'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}]}


In [11]:
d['k1']

[1,
 2,
 3,
 {'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}]

In [12]:
d['k1'][3]

{'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}

In [13]:
d['k1'][3]['tricky']


['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]

In [14]:
d['k1'][3]['tricky'][3]

{'target': [1, 2, 3, 'hello']}

In [15]:
d['k1'][3]['tricky'][3]['target']

[1, 2, 3, 'hello']

In [16]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [ ]:
#6. What is the main difference between a tuple and a list?
"Tupple is immutable"
'List is mutable'

In [23]:
#7. Create a function that grabs the email website domain from a string in the form: ** user@domain.com
def getDomain(s):
    return s.split('@')[1]
getDomain(input('enter your email add :'))

#or 
email = input("enter your email add : ")
email.split('@')[1]


enter your email add : bapusatsang@gmail.com
enter your email add :  mat.patel13@gmail.com


'gmail.com'

In [24]:
#8. Create a basic function that returns True if the word 'dog' is contained in the input string. Don't 
#worry about edge cases like a punctuation being attached to the word dog, but do account for 
#capitalization. : findDog('Is there a dog here?')
def findDog(s):
    return "dog" in s.lower()
findDog("Is there any Dog there ?")


True

In [25]:
#9. Use lambda expressions and the filter() function to filter out words from a list that don't start 
#with the letter 's'. For example:** seq = ['soup','dog','salad','cat','great']
seq = ['soup','dog','salad','cat','great']
list(filter(lambda s: s[0]=='s',seq))


['soup', 'salad']

In [27]:
#10. You are driving a little too fast, and a police officer stops you. Write a function to return one of 
#3 possible results: "No ticket", "Small ticket", or "Big Ticket". If your speed is 60 or less, the 
#result is "No Ticket". If speed is between 61 and 80 inclusive, the result is "Small Ticket". If 
#speed is 81 or more, the result is "Big Ticket". Unless it is your birthday (encoded as a boolean 
#value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all  cases.
def ticket(speed, birthday):
    if birthday is True:
        speed -= 5
    if speed > 80:
        return "Big Ticket"
    elif speed >60:
        return "Small Ticket"
    else :
        return "No Ticket"

ticket(66, True)


'Small Ticket'

In [28]:
ticket(81, False)


'Big Ticket'

In [28]:
#11. Write a program to input roll no, student name, marks of physics, chemistry and maths out of 
#100. (0-100). Calculate total, percentage, calculate STATUS (pass, fail) if students scores above 
#40 in all the 3 subjects the STATUS should be pass otherwise fail. Calculate GRADE if STATUS is pass.
#Grade must be based on percentage value if percentage is above 70, then grade must be DISTINCTION if percentage is above 60, then grade must 
#be FIRST CLASS if percentage is above 50, then grade must be SECOND CLASS if percentage is above 40, then grade must be PASS CLASS

def score(phy,chem,maths):
    total = phy + chem + maths
    percantage  =  total /3
    if (phy > 40) & (chem > 40) & (maths > 40):
        
        print('pass')
        if percantage > 70 :
            return "DISTINCTOIN"
        elif percantage > 60:
            return "FIRST CLASS"
        elif percantage > 50:
            return "SECOND CLASS"
        elif percantage > 40:
            return "PASS"       
            
    else :
        return "FAIL"

## calling class
phy = int(input("enter the physics marks : "))
chem = int(input('enter the chemistry marks :'))
maths = int(input ('enter the maths marks : '))
print(score(phy,chem,maths))

enter the physics marks :  2
enter the chemistry marks : 2
enter the maths marks :  2


FAIL


In [ ]:
empid = input('enter your empid : ')
name = input('enter your name : ')
basic = int(input('enter your basic salary : '))
no_of_exp = int(input('enter your no of experience : '))

# calculating 
hra = basic*0.35
da = basic * 0.58
pf = basic*0.095

# bonus 
if no_of_exp >= 30:
    bonus = basic*0.59    
elif no_of_exp >= 23:
   bonus = basic*0.51
elif no_of_exp >= 15:
    bonus = basic*0.45
elif no_of_exp >= 7:
    bonus = basic*0.3
else:
    bonus = basic*0.16

net_salary = basic + da + hra - pf + bonus
print("net salary : ",net_salary)

In [ ]:
#####    NUMPY    ##############

In [1]:
import numpy as np

In [2]:
pip intstall numpy

Note: you may need to restart the kernel to use updated packages.


ERROR: unknown command "intstall" - maybe you meant "install"



In [5]:
!py pip install numpy

C:\Users\P G Chopda\AppData\Local\Programs\Python\Python312\python.exe: can't open file 'D:\\Maitri folder\\jupyter notebook\\pip': [Errno 2] No such file or directory


In [6]:
import numpy as np

In [8]:
np.arange(0,13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
np.__version__


'2.0.1'

In [11]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [25]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [5]:
arr = np.arange(0,9).reshape(3,3)

In [6]:
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])