In [2]:
import numpy as np

In [17]:
np.arange(0,13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
np.__version__


'2.0.1'

In [4]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [10]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [12]:
arr = np.arange(0,9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:

ar1 = np.arange(10,dtype=float)
print(ar1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [14]:
arr = np.arange(0,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [16]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [19]:
l2=[x for x in range(0,10)]
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
l3=[str(x) for x in l2]
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [21]:
l4=[x for x in range(0,10,2)]
l4

[0, 2, 4, 6, 8]

In [22]:
l4 = [x**2 for x in range(0,10)]
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [13]:
import array

In [28]:
arr = array.array('i',l2)
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr = array.array('f',l2)
arr

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

In [30]:
type(arr)

array.array

In [38]:
arr
array.array('i',[x**2 for x in l2])

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [39]:
np.array (l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.array([x+3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
np.array([x-3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [43]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [44]:
np.array([1, 2, 3, 4],dtype = 'float')

array([1., 2., 3., 4.])

In [45]:
np.array([1, 2, 3, 4],dtype = 'str')

array(['1', '2', '3', '4'], dtype='<U1')

In [47]:
np.array([1, 2, 3, 4],dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [49]:
list = [[1,2,3,4],[4,5,6,7]]
list

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [51]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
lc = [range(i , i+3) for i in [1,3]]
lc

[range(1, 4), range(3, 6)]

In [55]:
np.array(lc)

array([[1, 2, 3],
       [3, 4, 5]])

In [57]:
lc = [range (i , i+3) for i in [1,9]]
lc


[range(1, 4), range(9, 12)]

In [58]:
lc = [range(i,i+3) for i in [1,9,3]]
lc

[range(1, 4), range(9, 12), range(3, 6)]

In [59]:
np.array(lc)

array([[ 1,  2,  3],
       [ 9, 10, 11],
       [ 3,  4,  5]])

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.zeros([2,2],dtype = 'int32')

array([[0, 0],
       [0, 0]], dtype=int32)

In [62]:
np.zeros([10,10],dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [63]:
np.zeros([3,4],dtype = 'int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [64]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [66]:
arr = np.zeros((10,10))
arr


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
arr[1:9,1:9] = 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
arr[2:8,2:8] = 2
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
arr[3:7,3:7] = 3
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [72]:
arr[4:6,4:6] = 4
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 4., 4., 3., 2., 1., 0.],
       [0., 1., 2., 3., 4., 4., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
ar = np.arange(0,9,dtype = 'float').reshape(3,3)
ar

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [75]:
ar[:] = 3.14
ar

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [76]:
np.full((3,4),'abc')


array([['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc']], dtype='<U3')

In [15]:
#identity matrix
#np.eye?

In [78]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
np.transpose(np.eye(3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#list
#list  comprehesion
#array modules(imported library array)
#numpy array (zeros,ones,full,eye,arange)
#reshape
#indexing

In [4]:
np.full([6,6],64)

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [5]:
#linspace - linearly spaced elements (start to end equal part)
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [6]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.linspace(0,0.1,5)

array([0.   , 0.025, 0.05 , 0.075, 0.1  ])

In [8]:
np.linspace(0,0.1,100,True)

array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
       0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
       0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
       0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
       0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424242,
       0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
       0.03030303, 0.03131313, 0.03232323, 0.03333333, 0.03434343,
       0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
       0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444444,
       0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
       0.05050505, 0.05151515, 0.05252525, 0.05353535, 0.05454545,
       0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
       0.06060606, 0.06161616, 0.06262626, 0.06363636, 0.06464646,
       0.06565657, 0.06666667, 0.06767677, 0.06868687, 0.06969697,
       0.07070707, 0.07171717, 0.07272727, 0.07373737, 0.07474

In [1]:
#np.linspace?

In [10]:
#first random - modul and second random - function name
np.random.random((3,3))

array([[0.9178054 , 0.1059269 , 0.87390845],
       [0.77660594, 0.07100523, 0.82290212],
       [0.11531746, 0.48374368, 0.54919549]])

In [11]:
np.random.random(3)

array([0.00543346, 0.51011103, 0.48407767])

In [12]:
np.random.random((2,2))
#values between 0 and 1

array([[0.26695411, 0.02566687],
       [0.22651377, 0.61498834]])

In [13]:
#values with mean 0 and std 1 normal ( start ,end , no of else)
np.random.normal(0,1,10)

array([ 0.65326111, -0.43846392, -0.44822218,  0.23804819, -0.25927978,
        0.79627376,  0.9831067 , -0.47017042, -0.92118759, -0.09889997])

In [16]:
np.random.normal(10)

9.454152595562048

In [17]:
np.random.normal(0,1,(2,2))

array([[-1.9302126 ,  1.49723669],
       [ 1.51533038, -1.05526064]])

In [18]:
# we can generate any random values that case we fix using random.seed
np.random.seed(10)
np.random.random(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [2]:
#np.random.randint?

In [20]:
np.random.randint(50,100,36)

array([86, 66, 86, 97, 61, 74, 93, 83, 58, 86, 64, 99, 63, 55, 63, 75, 63,
       78, 72, 80, 80, 75, 62, 51, 81, 86, 77, 68, 79, 63, 72, 73, 80, 61,
       78, 60], dtype=int32)

In [3]:
#np.random.randn?

In [ ]:
#operation on numpy array

In [23]:
arr = np.random.randint(0,100,20)
arr

array([71, 88, 88, 50, 54, 34, 15, 77, 88, 15,  6, 85, 22, 11, 12, 92, 96,
       62, 57, 79], dtype=int32)

In [25]:
arr = np.random.randint(0,100,(2,2))
arr

array([[45, 40],
       [89, 73]], dtype=int32)

In [26]:
#this attribute return number of dimension 
arr.ndim

2

In [27]:
#this attribute return number of elements in an arrow 
arr.size

4

In [28]:
arr.shape

(2, 2)

In [29]:
#return data type of array
arr.dtype

dtype('int32')

# array indexing

In [16]:
import array 

In [34]:
m = np.arange(0,40,4)
m

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [46]:
m[0]

np.int64(0)

In [42]:
print(m[4])

16


In [43]:
print(m[-1])

36


In [44]:
m[:4]

array([ 0,  4,  8, 12])

In [47]:
m[4:]

array([16, 20, 24, 28, 32, 36])

In [48]:
m[4:6]

array([16, 20])

In [50]:
m[4]=45
m

array([ 0,  4,  8, 12, 45, 20, 24, 28, 32, 36])

In [7]:
a = [1,2,3,4,5,6,7,8]
a

[1, 2, 3, 4, 5, 6, 7, 8]

In [8]:
a[2:6:2]

[3, 5]

In [9]:
a[::2]

[1, 3, 5, 7]

In [10]:
#reverse slicing 
a[::-1]

[8, 7, 6, 5, 4, 3, 2, 1]

In [11]:
a[::-2]

[8, 6, 4, 2]

In [3]:
### 2D array

a = np.arange(0,25).reshape(5,5)
a
 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
# for row -- [start , rando of row ]
a  [0,1:5]

array([1, 2, 3, 4])

In [36]:
# slicing [ row no, range ] 
# single number [ row no, col no]
a [2,1]

np.int64(11)

In [37]:
a [ 0:3,0]

array([ 0,  5, 10])

In [38]:
#double slicing
a[0:3, 0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [39]:
a[:3,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [40]:
a[2:5,3:6]

array([[13, 14],
       [18, 19],
       [23, 24]])

In [41]:
# even number (step size )
a[::2,::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [43]:
# skip 2 row 
a[::2,::]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [44]:
a[::,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [46]:
#reverse row 
a[::-1,::]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [47]:
#all element are reverse
a[::-1,::-1]

array([[24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [24]:
ar1 = np.arange(0,9).reshape(3,3)
ar1

# shallow copy and deep copy


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
ar2 = np.arange(10,19).reshape(3,3)
ar2


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [29]:
b = ar1[1:,1:]
b

array([[4, 5],
       [7, 8]])

In [39]:
# In the shallow we can change other sclising veriable than it automatically change in the 
# original matrix
b[1,1] = 455
ar1

array([[    0,     1,     2],
       [    3,     4, 23000],
       [    6,     7,   455]])

In [40]:
ar1[1,2] = 23000
ar1


array([[    0,     1,     2],
       [    3,     4, 23000],
       [    6,     7,   455]])

In [41]:
b

array([[    4, 23000],
       [    7,   455]])

In [47]:
# deep copy 
b = ar2[:2,:2]

array([[10, 11],
       [13, 14]])

In [48]:
b.copy()

array([[    4, 23000],
       [    7,   455]])

In [50]:
b [1,1] = 33
b

array([[    4, 23000],
       [    7,    33]])

In [51]:
ar2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [40]:
## reshape function 
t = np.arange(25).reshape(5,5)
t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
a  = np.arange(4)
a

array([0, 1, 2, 3])

In [59]:
a.reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

In [65]:
v = a.reshape(2,2)
v

array([[0, 1],
       [2, 3]])

In [67]:
c = v.reshape(1,4)
c

array([[0, 1, 2, 3]])

In [2]:
# Any type of array convert into 1D array use of this funciton
# ravel() , flatten()
#       np.ravel?

In [71]:
ar2.ravel()

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [72]:
ar1.flatten()

array([    0,     1,     2,     3,     4, 23000,     6,     7,    33])

In [82]:
# use for change the axis
a[:,np.newaxis]


array([[0],
       [1],
       [2],
       [3]])

In [77]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

In [83]:
# axis to specify row 0 / column1 
np.concatenate([ar1,ar2],axis = 0)

array([[    0,     1,     2],
       [    3,     4, 23000],
       [    6,     7,    33],
       [   10,    11,    12],
       [   13,    14,    15],
       [   16,    17,    18]])

In [84]:
np.concatenate([ar1,ar2],axis = 1)

array([[    0,     1,     2,    10,    11,    12],
       [    3,     4, 23000,    13,    14,    15],
       [    6,     7,    33,    16,    17,    18]])

In [1]:
import numpy as np

In [4]:
# stack array in sequence vertically (row wise)
#      np.vstack?

In [9]:
x = np.array([1,2,3])
grid = np.array([[4,5,6],[7,8,9]])
grid

array([[4, 5, 6],
       [7, 8, 9]])

In [11]:
np.vstack((x,grid))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
## append an element
np.hstack((x,[4]))

array([1, 2, 3, 4])

In [69]:
ar = np.array([[1,3],
                [2,4]])
ar

array([[1, 3],
       [2, 4]])

In [19]:
grid

array([[4, 5, 6],
       [7, 8, 9]])

In [20]:
x

array([1, 2, 3])

In [22]:
np.hstack([ar,grid])

array([[1, 3, 4, 5, 6],
       [2, 4, 7, 8, 9]])

In [24]:
# np.hspite , np.vsplit , np.split

In [25]:
#  np.hsplit?

In [27]:
#  np.vsplit?

In [29]:
 np.split?

Signature:       np.split(ary, indices_or_sections, axis=0)
Call signature:  np.split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function split at 0x0000022C7EE8E660>
File:            c:\users\p g chopda\appdata\local\programs\python\python312\lib\site-packages\numpy\lib\_shape_base_impl.py
Docstring:      
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

    - ary[:2]
    - ary[2:3]
    - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an em

In [35]:
ar = np.arange(1,6)
ar

array([1, 2, 3, 4, 5])

In [36]:
np.split(ar,5)

[array([1]), array([2]), array([3]), array([4]), array([5])]

In [37]:
np.split(ar,[2,3])

[array([1, 2]), array([3]), array([4, 5])]

In [38]:
np.split(ar,[1,4])

[array([1]), array([2, 3, 4]), array([5])]

In [39]:
np.split(ar,[1,2,4])

[array([1]), array([2]), array([3, 4]), array([5])]

In [47]:
t = np.arange(25).reshape(5,5)
t

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
np.split(t,(2,3))

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [60]:
np.hsplit(t,(2,4))

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18],
        [22, 23]]),
 array([[ 4],
        [ 9],
        [14],
        [19],
        [24]])]

In [62]:
np.vsplit(t,(2,4,4))

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([], shape=(0, 5), dtype=int64),
 array([[20, 21, 22, 23, 24]])]

# universal function
sum
mean
sd
variance
trignometric
log
aggrigation

In [65]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [68]:
np.sum(ar)

np.int64(15)

In [70]:
# row wise sum
np.sum(grid,axis = 0)

array([11, 13, 15])

In [71]:
# column wise sum
np.sum(grid,axis =1)

array([15, 24])

In [72]:
np.max(ar)

np.int64(4)

In [73]:
np.min(ar)

np.int64(1)

In [77]:
np.min(grid,axis = 0)

array([4, 5, 6])

In [78]:
np.max(grid,axis = 1)

array([6, 9])

In [79]:
# index of min
np.argmin(ar)  

np.int64(0)

In [80]:
np.argmin(grid)

np.int64(0)

In [81]:
np.argmax(grid)

np.int64(5)

In [82]:
np.argmax(grid)

np.int64(5)

In [83]:
b= -34
np.abs (b)

np.int64(34)

In [84]:
np.absolute(b)

np.int64(34)

In [85]:
# variance
np.var(ar)

np.float64(1.25)

In [86]:
# standard deviation
np.std(ar)

np.float64(1.118033988749895)

In [87]:
np.median(ar)

np.float64(2.5)

In [88]:
np.prod(ar)

np.int64(24)

In [89]:
# aggrigation are 1 mark question

# numpy assignment-1

In [1]:
import numpy as np

In [2]:
# 1. Create 1-D, 2-D and 3-D numpy array
d1 = np.arange(0,5)
d1

array([0, 1, 2, 3, 4])

In [3]:
# 2D array
d2 = np.arange(1,5).reshape(2,2) 
d2

array([[1, 2],
       [3, 4]])

In [4]:
# 3D array
d3 = np.arange(0,9).reshape(3,3)
d3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# 2. Print data type of array.
print(type(d1))
print(type(d2))
print(type(d3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [6]:
# 3. Print shape and dimensions of all the three different array.
d1.ndim

1

In [7]:
d2.ndim

2

In [8]:
d3.ndim

2

In [9]:
# 4. Create another 1-D array of 12 elements filled with zero
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
# 5. Create another 2-D array elements filled with ones.

np.ones(4).reshape(2,2)


array([[1., 1.],
       [1., 1.]])

In [11]:
# 6. Create a 1-D array known as Maths Marks out of 100 having 20 elements.

In [12]:
# 7. Sort the above array in ascending and descending order.
t = np.random.randint(0,23,10)
t


array([11,  3, 16,  6,  4, 22, 14, 21,  7, 18], dtype=int32)

In [13]:
# 8. Create a copy of sorted array to another variable by deep copying.
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
da = a[:2,:2].copy()
da

array([[0, 1],
       [3, 4]])

In [15]:
# 9. Create 2-D array of 5x5 which is an identify matrix and then convert to 1-D array.
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
i.ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [17]:
# 10. Create 2-D array of 3x3. Add one more row to it.
m = np.arange(4).reshape(2,2)
m
n = np.arange(11,13).reshape(2,1)
n
np.concatenate([m,n],1)

array([[ 0,  1, 11],
       [ 2,  3, 12]])

In [ ]:
# 11. Split above array created vertically and horizontally.

In [18]:
import numpy as np

In [19]:
# 12. Create 4x4 identity matrix. Add 4 to each element.
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# 13. Create 1-D array. Initialize with floating point values. Display its ceil, floor and 
#round (with 2 decimal's).


In [ ]:
# 14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise.

In [ ]:
# 15. Create a null vector of size 10 with 6th value filled with 200.

In [ ]:
# 16. Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence.

In [ ]:
# 17. Reverse the above vector.

In [20]:
# 18. Create a 5x5 matrix with values ranging from 0-24 using some function.
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# 19. Find indices of nonzero elements from [1,0,2,0,0,4,0,8]

In [32]:
# 20. Create a 10x10 matrix with 1 on the borders and 0 inside.
m = np.ones([10,10])
m[1:9:,1:9] = 0
m

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
# 21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern.
n = np.ones([8,8])
n
n[0:7:2,0:7:2] = 0
n

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [62]:
n = np.ones([8,8])
n
n[0:7:2,] = 0
n

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
#22. Create two 3x3 matrix with random integer values. Perform matrix addition, 
#multiplication and subtraction
ar1 = np.arange(0,9).reshape(3,3)
ar2 = np.arange(10,19).reshape(3,3)
ar1


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
ar2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [27]:
# additon 
ar1 + ar2


array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26]])

In [26]:
#subtraction
ar1-ar2

array([[-10, -10, -10],
       [-10, -10, -10],
       [-10, -10, -10]])

In [25]:
#multiplicaiotn
np.dot(ar1,ar2)

array([[ 45,  48,  51],
       [162, 174, 186],
       [279, 300, 321]])

# Numpy Excise 

In [63]:
# 1. import numpy as np
import numpy as np

In [64]:
# create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [65]:
# create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [66]:
# create an array of the integers from 10 to 50
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [67]:
#5.Create an array of all the even integers from 10 to 50
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [68]:
#6.Create a 3x3 matrix with values ranging from 0 to 8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [69]:
# 7. Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [70]:
# 8. use NumPy to generate a random number between 0 to 1
np.random.random(1)

array([0.3691554])

In [71]:
# 9. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution 
np.random.normal(0,100,25)

array([-122.49856881,  125.5269796 ,   42.48992345,   12.50622449,
        -51.54733301,  103.13941968,   56.58274097,  -90.51799644,
       -189.98954866,   87.86218495, -143.21378801,  -59.90186832,
         34.40952288,    1.54818795,   81.33155119,    3.57129129,
        -51.49549026,  -36.82177428,   48.0899029 ,  127.69569469,
       -151.72840258, -116.82078532,  -11.0940614 ,  -78.72835403,
        -83.11792965])

In [72]:
#10. Create a matrix of 10x10 matrix of linearly spaced elements from
#0.01 to 1 
np.linspace(0.01,1,100,True).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [73]:
# 11. Create an array of 20 linearly spaced points between 0 and 1
np.linspace(0,1,20,True)



array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [74]:
#12.Create a 5x5 matrix as
#array([[ 1, 2, 3, 4, 5],[ 6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20],
# [21, 22, 23, 24, 25]])

a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
#find following using slicing
#a. array([[12, 13, 14, 15],
# [17, 18, 19, 20],
# [22, 23, 24, 25]])

a[2:,1:]


array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [81]:
# b. 20
a[3,4]

np.int64(20)

In [82]:
#c.array([[ 2], [ 7], [12]])

In [83]:
# d.array([21, 22, 23, 24, 25])
a[4:,:]

array([[21, 22, 23, 24, 25]])

In [84]:
# e.array([[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]) 
a[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [85]:
# 13. Get sum of all values in matrix
np.sum(a)

np.int64(325)

In [88]:
# 14. Get sum of all the columns in matrix
np.sum(a,axis = 0)

array([55, 60, 65, 70, 75])

In [97]:
# 15. Get Standard deviation , varience , minimum, maximum from matrix row wis.
np.std(a,axis = 0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [98]:
np.var(a,axis = 0)

array([50., 50., 50., 50., 50.])

In [99]:
np.min(a)

np.int64(1)

In [100]:
np.max(a)

np.int64(25)

In [ ]:
# 16. create 2 d matrix with all border values nan and