# assignment 1


In [1]:
import numpy as np

In [4]:
# 1. Create 1-D, 2-D and 3-D numpy array
d1 = np.arange(0,5)
d1

array([0, 1, 2, 3, 4])

In [7]:
# 2D array
d2 = np.arange(1,5).reshape(2,2) 
d2

array([[1, 2],
       [3, 4]])

In [8]:
# 3D array
d3 = np.arange(0,9).reshape(3,3)
d3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
# 2. Print data type of array.
print(type(d1))
print(type(d2))
print(type(d3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [16]:
# 3. Print shape and dimensions of all the three different array.
d1.ndim

1

In [14]:
d2.ndim

2

In [15]:
d3.ndim

2

In [17]:
# 4. Create another 1-D array of 12 elements filled with zero
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# 5. Create another 2-D array elements filled with ones.

np.ones(4).reshape(2,2)


array([[1., 1.],
       [1., 1.]])

In [ ]:
# 6. Create a 1-D array known as Maths Marks out of 100 having 20 elements.



In [ ]:
# 7. Sort the above array in ascending and descending order.



In [21]:
# 8. Create a copy of sorted array to another variable by deep copying.
a = np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
da = a[:2,:2].copy()
da

array([[0, 1],
       [3, 4]])

In [39]:
# 9. Create 2-D array of 5x5 which is an identify matrix and then convert to 1-D array.
i = np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
i.ravel()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [ ]:
# 10. Create 2-D array of 3x3. Add one more row to it.