In [19]:
import numpy as np

In [3]:
np.arange(0,13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [3]:
np.__version__


'2.0.1'

In [4]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [10]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [12]:
arr = np.arange(0,9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:

ar1 = np.arange(10,dtype=float)
print(ar1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [14]:
arr = np.arange(0,100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [15]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [16]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [18]:
l = [1,2,3,4,5]
l

[1, 2, 3, 4, 5]

In [19]:
l2=[x for x in range(0,10)]
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
l3=[str(x) for x in l2]
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [21]:
l4=[x for x in range(0,10,2)]
l4

[0, 2, 4, 6, 8]

In [22]:
l4 = [x**2 for x in range(0,10)]
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [27]:
import array

In [28]:
arr = array.array('i',l2)
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr = array.array('f',l2)
arr

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

In [30]:
type(arr)

array.array

In [38]:
arr
array.array('i',[x**2 for x in l2])

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [39]:
np.array (l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.array([x+3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
np.array([x-3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [43]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [44]:
np.array([1, 2, 3, 4],dtype = 'float')

array([1., 2., 3., 4.])

In [45]:
np.array([1, 2, 3, 4],dtype = 'str')

array(['1', '2', '3', '4'], dtype='<U1')

In [47]:
np.array([1, 2, 3, 4],dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [49]:
list = [[1,2,3,4],[4,5,6,7]]
list

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [51]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
lc = [range(i , i+3) for i in [1,3]]
lc

[range(1, 4), range(3, 6)]

In [55]:
np.array(lc)

array([[1, 2, 3],
       [3, 4, 5]])

In [57]:
lc = [range (i , i+3) for i in [1,9]]
lc


[range(1, 4), range(9, 12)]

In [58]:
lc = [range(i,i+3) for i in [1,9,3]]
lc

[range(1, 4), range(9, 12), range(3, 6)]

In [59]:
np.array(lc)

array([[ 1,  2,  3],
       [ 9, 10, 11],
       [ 3,  4,  5]])

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.zeros([2,2],dtype = 'int32')

array([[0, 0],
       [0, 0]], dtype=int32)

In [62]:
np.zeros([10,10],dtype = 'int32')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [63]:
np.zeros([3,4],dtype = 'int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [64]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [66]:
arr = np.zeros((10,10))
arr


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
arr[1:9,1:9] = 1
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [70]:
arr[2:8,2:8] = 2
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
arr[3:7,3:7] = 3
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [72]:
arr[4:6,4:6] = 4
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 3., 4., 4., 3., 2., 1., 0.],
       [0., 1., 2., 3., 4., 4., 3., 2., 1., 0.],
       [0., 1., 2., 3., 3., 3., 3., 2., 1., 0.],
       [0., 1., 2., 2., 2., 2., 2., 2., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [73]:
ar = np.arange(0,9,dtype = 'float').reshape(3,3)
ar

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [75]:
ar[:] = 3.14
ar

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [76]:
np.full((3,4),'abc')


array([['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc'],
       ['abc', 'abc', 'abc', 'abc']], dtype='<U3')

In [15]:
#identity matrix
#np.eye?

In [78]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [80]:
np.transpose(np.eye(3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#list
#list  comprehesion
#array modules(imported library array)
#numpy array (zeros,ones,full,eye,arange)
#reshape
#indexing

In [4]:
np.full([6,6],64)

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [5]:
#linspace - linearly spaced elements (start to end equal part)
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [6]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.linspace(0,0.1,5)

array([0.   , 0.025, 0.05 , 0.075, 0.1  ])

In [8]:
np.linspace(0,0.1,100,True)

array([0.        , 0.0010101 , 0.0020202 , 0.0030303 , 0.0040404 ,
       0.00505051, 0.00606061, 0.00707071, 0.00808081, 0.00909091,
       0.01010101, 0.01111111, 0.01212121, 0.01313131, 0.01414141,
       0.01515152, 0.01616162, 0.01717172, 0.01818182, 0.01919192,
       0.02020202, 0.02121212, 0.02222222, 0.02323232, 0.02424242,
       0.02525253, 0.02626263, 0.02727273, 0.02828283, 0.02929293,
       0.03030303, 0.03131313, 0.03232323, 0.03333333, 0.03434343,
       0.03535354, 0.03636364, 0.03737374, 0.03838384, 0.03939394,
       0.04040404, 0.04141414, 0.04242424, 0.04343434, 0.04444444,
       0.04545455, 0.04646465, 0.04747475, 0.04848485, 0.04949495,
       0.05050505, 0.05151515, 0.05252525, 0.05353535, 0.05454545,
       0.05555556, 0.05656566, 0.05757576, 0.05858586, 0.05959596,
       0.06060606, 0.06161616, 0.06262626, 0.06363636, 0.06464646,
       0.06565657, 0.06666667, 0.06767677, 0.06868687, 0.06969697,
       0.07070707, 0.07171717, 0.07272727, 0.07373737, 0.07474

In [1]:
#np.linspace?

In [10]:
#first random - modul and second random - function name
np.random.random((3,3))

array([[0.9178054 , 0.1059269 , 0.87390845],
       [0.77660594, 0.07100523, 0.82290212],
       [0.11531746, 0.48374368, 0.54919549]])

In [11]:
np.random.random(3)

array([0.00543346, 0.51011103, 0.48407767])

In [12]:
np.random.random((2,2))
#values between 0 and 1

array([[0.26695411, 0.02566687],
       [0.22651377, 0.61498834]])

In [13]:
#values with mean 0 and std 1 normal ( start ,end , no of else)
np.random.normal(0,1,10)

array([ 0.65326111, -0.43846392, -0.44822218,  0.23804819, -0.25927978,
        0.79627376,  0.9831067 , -0.47017042, -0.92118759, -0.09889997])

In [16]:
np.random.normal(10)

9.454152595562048

In [17]:
np.random.normal(0,1,(2,2))

array([[-1.9302126 ,  1.49723669],
       [ 1.51533038, -1.05526064]])

In [18]:
# we can generate any random values that case we fix using random.seed
np.random.seed(10)
np.random.random(10)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981])

In [2]:
#np.random.randint?

In [20]:
np.random.randint(50,100,36)

array([86, 66, 86, 97, 61, 74, 93, 83, 58, 86, 64, 99, 63, 55, 63, 75, 63,
       78, 72, 80, 80, 75, 62, 51, 81, 86, 77, 68, 79, 63, 72, 73, 80, 61,
       78, 60], dtype=int32)

In [3]:
#np.random.randn?

In [ ]:
#operation on numpy array

In [23]:
arr = np.random.randint(0,100,20)
arr

array([71, 88, 88, 50, 54, 34, 15, 77, 88, 15,  6, 85, 22, 11, 12, 92, 96,
       62, 57, 79], dtype=int32)

In [25]:
arr = np.random.randint(0,100,(2,2))
arr

array([[45, 40],
       [89, 73]], dtype=int32)

In [26]:
#this attribute return number of dimension 
arr.ndim

2

In [27]:
#this attribute return number of elements in an arrow 
arr.size

4

In [28]:
arr.shape

(2, 2)

In [29]:
#return data type of array
arr.dtype

dtype('int32')

# array indexing

In [16]:
import array 

In [34]:
m = np.arange(0,40,4)
m

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [46]:
m[0]

np.int64(0)

In [42]:
print(m[4])

16


In [43]:
print(m[-1])

36


In [44]:
m[:4]

array([ 0,  4,  8, 12])

In [47]:
m[4:]

array([16, 20, 24, 28, 32, 36])

In [48]:
m[4:6]

array([16, 20])

In [50]:
m[4]=45
m

array([ 0,  4,  8, 12, 45, 20, 24, 28, 32, 36])