In [4]:
#pip install pandas

In [5]:
import pandas as pd

In [6]:
s1 =  pd.Series([1,2,3,34,4])
s1

0     1
1     2
2     3
3    34
4     4
dtype: int64

In [7]:
s1[2]

np.int64(3)

In [8]:
s1.values

array([ 1,  2,  3, 34,  4])

In [9]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
import numpy as np

In [11]:
marks = np.arange(30,50,2)
marks

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [12]:
smarks = pd.Series(marks)
smarks


0    30
1    32
2    34
3    36
4    38
5    40
6    42
7    44
8    46
9    48
dtype: int64

In [13]:
s1.value_counts

<bound method IndexOpsMixin.value_counts of 0     1
1     2
2     3
3    34
4     4
dtype: int64>

In [14]:
s2 = pd.Series (index = ['x','y','z'],data = [1,2,3])
s2

x    1
y    2
z    3
dtype: int64

In [15]:
display(s2.values , s2.index , s2)

array([1, 2, 3])

Index(['x', 'y', 'z'], dtype='object')

x    1
y    2
z    3
dtype: int64

In [16]:
#here firs values is data and second values is index
s3 = pd.Series ( ['x','y','z'], [1,2,3])
s3

1    x
2    y
3    z
dtype: object

In [17]:
display(s3,s3.values,s3.index)

1    x
2    y
3    z
dtype: object

array(['x', 'y', 'z'], dtype=object)

Index([1, 2, 3], dtype='int64')

In [18]:
s3.values

array(['x', 'y', 'z'], dtype=object)

In [19]:
s3[2]

'y'

In [20]:
s3[:3]

1    x
2    y
3    z
dtype: object

In [21]:
s3[1:3]

2    y
3    z
dtype: object

In [22]:
dic = {"Maitri" : "A" , "Jiya" : "A+" , "Sakshi" : "A"}
dic

{'Maitri': 'A', 'Jiya': 'A+', 'Sakshi': 'A'}

In [23]:
pd.Series(dic)

Maitri     A
Jiya      A+
Sakshi     A
dtype: object

In [24]:
data = ['A+','A++','A']
ind = ['Maitri','jiya','sakshi']
pd.Series(data,ind)

Maitri     A+
jiya      A++
sakshi      A
dtype: object

In [25]:
pd.Series(ind,data)

A+     Maitri
A++      jiya
A      sakshi
dtype: object

In [26]:
display(pd.Series(ind,data).index)

Index(['A+', 'A++', 'A'], dtype='object')

In [27]:
display(pd.Series(ind,data).values)

array(['Maitri', 'jiya', 'sakshi'], dtype=object)

In [28]:
tup = ('t','u','p','l','e')
tup

('t', 'u', 'p', 'l', 'e')

In [29]:
pd.Series(tup)

0    t
1    u
2    p
3    l
4    e
dtype: object

In [30]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [31]:
pd.DataFrame({'riya':[50,53],'sia' : [1,2]})

riya  sia
0    50    1
1    53    2

In [30]:
pd.DataFrame({'riya':[50,53],'sia' : [1,2]}, index= ["Python","Fds"])

riya  sia
Python    50    1
Fds       53    2

In [47]:
pd.DataFrame([[24,23],[45,56]],columns = ['A','B'], index = ['Py','Ds'])

A   B
Py  24  23
Ds  45  56

In [48]:
import numpy as np

In [53]:
np.random.seed(9)
marks = pd.DataFrame(np.random.randint(0,30,(3,3)),index = ['Maitri','Jiya','Sakshi'],columns = ['Py','Fds','Cai'])
marks

Py  Fds  Cai
Maitri  28   21   22
Jiya    24   27   22
Sakshi  29    1   22

In [54]:
marks.columns

Index(['Py', 'Fds', 'Cai'], dtype='object')

In [55]:
marks.values

array([[28, 21, 22],
       [24, 27, 22],
       [29,  1, 22]], dtype=int32)

In [56]:
marks.index

Index(['Maitri', 'Jiya', 'Sakshi'], dtype='object')

In [57]:
marks['Py']

Maitri    28
Jiya      24
Sakshi    29
Name: Py, dtype: int32

In [58]:
marks['Fds']

Maitri    21
Jiya      27
Sakshi     1
Name: Fds, dtype: int32

In [59]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
pd.DataFrame(a,index = [1,2,3,4,5],columns = ['a','b','c','d','e'])

a   b   c   d   e
1   0   1   2   3   4
2   5   6   7   8   9
3  10  11  12  13  14
4  15  16  17  18  19
5  20  21  22  23  24

In [61]:
marks['total'] = marks['Py']+marks['Fds']+marks['Cai']
marks

Py  Fds  Cai  total
Maitri  28   21   22     71
Jiya    24   27   22     73
Sakshi  29    1   22     52

In [62]:
marks['percentage'] = marks['total'] / 100
marks

Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71
Jiya    24   27   22     73        0.73
Sakshi  29    1   22     52        0.52

In [63]:
# indexing & selection

marks[['Py' , 'Fds']]

Py  Fds
Maitri  28   21
Jiya    24   27
Sakshi  29    1

# we have three function in indexing and selection 
dataframe_name.loc
---> in loc we  put lable
  dataframe_name.iloc
---> in iloc we put index no / numeric

dataframe_name.ix
---> in ix we put both 


In [64]:
#pd.DataFrame.loc?

In [65]:
#pd.DataFrame.iloc?

In [66]:
marks.loc['Jiya']

Py            24.00
Fds           27.00
Cai           22.00
total         73.00
percentage     0.73
Name: Jiya, dtype: float64

In [67]:
marks.loc['Jiya','Py']

np.int32(24)

In [68]:
marks.loc['Jiya','Py':'Cai']

Py     24.0
Fds    27.0
Cai    22.0
Name: Jiya, dtype: float64

In [69]:
marks.loc[:'Maitri',['Py','Fds']]

Py  Fds
Maitri  28   21

In [70]:
marks.loc[:'Maitri','Py':]


Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71

In [71]:
marks.loc['Jiya','Py':'Cai']

Py     24.0
Fds    27.0
Cai    22.0
Name: Jiya, dtype: float64

In [72]:
marks.iloc[:2]

Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71
Jiya    24   27   22     73        0.73

In [73]:
marks.iloc[:2,1:3]

Fds  Cai
Maitri   21   22
Jiya     27   22

In [74]:
marks.iloc[:2,0:3]

Py  Fds  Cai
Maitri  28   21   22
Jiya    24   27   22

In [75]:
marks.iloc[:,3]

Maitri    71
Jiya      73
Sakshi    52
Name: total, dtype: int32

In [76]:
marks.iloc[:,3]>16


Maitri    True
Jiya      True
Sakshi    True
Name: total, dtype: bool

In [57]:
marks[marks.Py>25]   # first method

Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71
Sakshi  29    1   22     52        0.52

In [58]:
marks[marks['Py']>25]  #second methon

Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71
Sakshi  29    1   22     52        0.52

# Assignment Excise 

In [59]:
import pandas as pd

In [60]:
import numpy as np

In [71]:
#Q. 1
prod = ['ALOE BARRY NECTOR' , 'FOREVER GEL' , 'ALOE PEACHES','ALOE MANGO']
prid = ['FL01','FL02','FL03','FL04']
price = [1000,1100,1120,1130] 
c = np.array(price)
c


array([1000, 1100, 1120, 1130])

In [72]:
product = pd.DataFrame(prod, prid,columns = ['Product name'])
product
product['price'] = price
product

Product name  price
FL01  ALOE BARRY NECTOR   1000
FL02        FOREVER GEL   1100
FL03       ALOE PEACHES   1120
FL04         ALOE MANGO   1130

In [85]:
# q.2 
product['Product name']

FL01    ALOE BARRY NECTOR
FL02          FOREVER GEL
FL03         ALOE PEACHES
FL04           ALOE MANGO
Name: Product name, dtype: object

In [86]:
# q. 7
product.loc["FL01" : "FL03"]

Product name  price
FL01  ALOE BARRY NECTOR   1000
FL02        FOREVER GEL   1100
FL03       ALOE PEACHES   1120

In [95]:
# q.8
product.iloc[2,1]

np.int64(1120)

In [96]:
# q. 9
product.iloc[2:,1]

FL03    1120
FL04    1130
Name: price, dtype: int64

In [98]:
# q. 10
product.iloc[:,0]

FL01    ALOE BARRY NECTOR
FL02          FOREVER GEL
FL03         ALOE PEACHES
FL04           ALOE MANGO
Name: Product name, dtype: object

In [63]:
# q.10

np.random.seed(15)
mark = pd.DataFrame(np.random.randint(0,50,(5,3)),index = ['Maitri','Jiya','Sakshi','Jonty','Man'],columns = ['Py','Fds','Cai'])
mark

Py  Fds  Cai
Maitri   8   12    5
Jiya     0   28   27
Sakshi   7   11   21
Jonty   47   29   17
Man     45   31   23

In [64]:
#11
mark[mark['Py']<20 ] = 21


In [65]:
mark

Py  Fds  Cai
Maitri  21   21   21
Jiya    21   21   21
Sakshi  21   21   21
Jonty   47   29   17
Man     45   31   23

In [66]:
# 12
mark+2

Py  Fds  Cai
Maitri  23   23   23
Jiya    23   23   23
Sakshi  23   23   23
Jonty   49   31   19
Man     47   33   25

In [67]:
#q. 13
mark[mark['Py']>30 ]

Py  Fds  Cai
Jonty  47   29   17
Man    45   31   23

In [68]:
#q.13
mark[mark['Fds']>30 ]

Py  Fds  Cai
Man  45   31   23

In [69]:
#q. 14
mark['per'] = (mark['Py']+mark['Fds']+mark['Cai']) / 100
mark['per']

Maitri    0.63
Jiya      0.63
Sakshi    0.63
Jonty     0.93
Man       0.99
Name: per, dtype: float64

In [70]:
mark['per']

Maitri    0.63
Jiya      0.63
Sakshi    0.63
Jonty     0.93
Man       0.99
Name: per, dtype: float64

# opration on series and data frames

In [2]:
import pandas as pd
import numpy as np

In [3]:
rng = np.random.RandomState(42)

In [4]:
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [5]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns = ['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [6]:
# exponencial funciton
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [7]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [8]:
area = pd.Series({'Uttar Pradesh':243268,'Maharashtra' : 307713,'Bihar':94163},name = "area")
area

Uttar Pradesh    243268
Maharashtra      307713
Bihar             94163
Name: area, dtype: int64

In [9]:
population =  pd.Series({'West Bengal':91276115,'Maharashtra':124484447,'Bihar':104099452},name = "population")
population

West Bengal     91276115
Maharashtra    124484447
Bihar          104099452
Name: population, dtype: int64

In [10]:
population_density = population / area
population_density

Bihar            1105.523953
Maharashtra       404.547247
Uttar Pradesh            NaN
West Bengal              NaN
dtype: float64

In [11]:
A = pd.Series([2,4,6],index = [0,1,2])
B = pd.Series([1,3,5],index = [1,2,3])

In [12]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [13]:
# add() and fill method we use it. Then it is automatically fill nan values
A.add(B,fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [14]:
A = pd.DataFrame(rng.randint(0,15,(2,2)),columns = list('AB'))
B = pd.DataFrame(rng.randint(0,10,(3,3)),columns = list('BAC'))

In [15]:
A + B

A     B   C
0   2.0  12.0 NaN
1  20.0  13.0 NaN
2   NaN   NaN NaN

In [16]:
fill = A.stack().mean() # converts df A into a series with all values stacked vertically calculates the mean


In [17]:
A.add(B,fill_value = fill)

A     B     C
0   2.0  12.0  12.0
1  20.0  13.0  13.0
2   8.0  16.0  17.0

In [18]:
A = np.random.randint(10,size = (3,4))
A

array([[6, 6, 5, 6],
       [9, 3, 7, 2],
       [2, 7, 3, 5]], dtype=int32)

In [19]:
# this is subtract only row wise 
A - A[0]

array([[ 0,  0,  0,  0],
       [ 3, -3,  2, -4],
       [-4,  1, -2, -1]], dtype=int32)

In [19]:
df = pd.DataFrame(A,columns = list('QRST'))
df

Q  R  S  T
0  9  6  7  3
1  7  1  6  7
2  6  4  7  8

In [20]:
df - df.iloc[0] # subtraction is applied row wise by default 

Q  R  S  T
0  0  0  0  0
1 -2 -5 -1  4
2 -3 -2  0  5

In [21]:
df.subtract(df['R'],axis = 0) # column wise operations, we can use axis keyword

Q  R  S  T
0  3  0  1 -3
1  6  0  5  6
2  2  0  3  4

In [22]:
halfrow = df.iloc[0,::2] #select every other element from first row i.e. Q and S from 1st row 
halfrow

Q    9
S    7
Name: 0, dtype: int32

In [23]:
df - halfrow # operation - subtraction

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -2.0 NaN -1.0 NaN
2 -3.0 NaN  0.0 NaN

In [41]:
import pandas as pd
import numpy as np

In [42]:
# sentinal value
vals1 = np.array([1,None,2,3])
vals1

array([1, None, 2, 3], dtype=object)

In [20]:
# This is used to measure the execution time of creating a large NumPy array and summing its elements
%timeit np.arange(1E6,dtype = int).sum()

3.35 ms ± 520 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [22]:
# This is used to measure the execution time of creating a large NumPy array and summing its elements but it is slower than int data type 
%timeit np.arange(1E6,dtype = object).sum()

68 ms ± 6.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
# this is give you error because here in the array we have nan value
vals1.sum()

NameError: name 'vals1' is not defined

In [24]:
# NaN - it special floating point value return and missing value is nan
vals2 = np.array([1,np.nan,3,4])
vals2

array([ 1., nan,  3.,  4.])

In [25]:
1 + np.nan

nan

In [48]:
0*np.nan

nan

In [49]:
# this means that aggregates over the values are well defined
vals2.sum(),vals2.min(),vals2.max()


(np.float64(nan), np.float64(nan), np.float64(nan))

In [39]:
# this function are does in code is all nan values are ignor and In the remaining value apply sum , min , max fun 
np.nansum(vals2) , np.nanmin(vals2),np.nanmax(vals2)

(np.float64(8.0), np.float64(1.0), np.float64(4.0))

In [33]:
# here is a series of integers with missing data, created from a list containing all three available markers 
# if Int32 - missing value or int32 - non missing value
pd.Series ([1,np.nan,2,None , pd.NA],dtype = "Int32")

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

# operation on null values
isnull - generates a boolean mask indicating missing values
notnull - opposite of isnull
dropna - returns a filtered version of the data 
fillna - returns a vopy of the data with messing values filled or imputed

In [50]:
import pandas as pd
import numpy as np

In [51]:
data = pd.Series ([1,np.nan,"Hello",None])

In [52]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [53]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [54]:
# dropping null values
data.dropna()

0        1
2    Hello
dtype: object

In [55]:
# fill the na value with some number 
data.fillna(3)

0        1
1        3
2    Hello
3        3
dtype: object

In [58]:

data[data.notnull()]

0        1
2    Hello
dtype: object

In [57]:
df = pd.DataFrame([[1,np.nan,2],
                  [2,3,4],
                  [np.nan,4,np.nan]])
df

0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  4.0
2  NaN  4.0  NaN

In [12]:
# it is dropping the whole row in nan values
df.dropna()

0    1    2
1  2.0  3.0  4.0

In [13]:
df.dropna(axis = 'columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2]

In [56]:
df[3] = np.nan
df

0    1    2   3
0  1.0  NaN  2.0 NaN
1  2.0  3.0  4.0 NaN
2  NaN  4.0  NaN NaN

In [62]:
# "how" is use for erase all nan value columns and returns other columns
df.dropna(axis = 'columns',how = 'all')

0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  4.0
2  NaN  4.0  NaN

In [65]:
# this method is return non null value row in the matrix
df.dropna(axis = "rows",thresh = 3)

0    1    2
1  2.0  3.0  4.0

In [66]:
data = pd.Series([1,np.nan,2,None,3],index = list("abcde"),dtype = "Int32")
data

a       1
b    <NA>
c       2
d    <NA>
e       3
dtype: Int32

In [67]:
# we can fil NA entries with a single value, such as Zero
data.fillna(0)

a    1
b    0
c    2
d    0
e    3
dtype: Int32

In [68]:
# we can specify a forward fill to propagate the previous value forward
data.fillna(method = "ffill")

C:\Users\P G Chopda\AppData\Local\Temp\ipykernel_20908\2060402518.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method = "ffill")


a    1
b    1
c    2
d    2
e    3
dtype: Int32

In [69]:
# or we can specify a backward fill to propagate the next values backward
data.fillna(method = "bfill")

C:\Users\P G Chopda\AppData\Local\Temp\ipykernel_20908\3926945000.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method = "bfill")


a    1
b    2
c    2
d    3
e    3
dtype: Int32

In [70]:
df

0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  4.0
2  NaN  4.0  NaN

In [17]:
# it is fill values column wise here show last row middle 0.4 we have it and using this method we fill last element (2,2) it fill it 
df.fillna(method = "ffill",axis = 1)

C:\Users\P G Chopda\AppData\Local\Temp\ipykernel_20908\2557622704.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill",axis = 1)


0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  4.0
2  NaN  4.0  4.0

In [71]:
# it is fill values row wise here show up to down fill the value
df.fillna(method = "ffill",axis = 0)

C:\Users\P G Chopda\AppData\Local\Temp\ipykernel_20908\2475783299.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = "ffill",axis = 0)


0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  4.0
2  2.0  4.0  4.0

# Lab Practice for Handling Missing Data

In [72]:
# Working with Series
import pandas as pd
import numpy as np

In [26]:
# Create a Series of your choice
sr1 = pd.Series(np.arange(1,10))
sr2 = pd.Series(np.arange(11,20))

In [27]:
# 2. Calculate the sum of the Series.
sr1 + sr2

0    12
1    14
2    16
3    18
4    20
5    22
6    24
7    26
8    28
dtype: int64

In [75]:
# 3. Calculate the mean of the Series
np.mean(sr1) ,np.mean(sr2)

(np.float64(5.0), np.float64(15.0))

In [76]:
# 4. Determine the minimum value in the Series. 
np.min(sr1) , np.min(sr2)

(np.int64(1), np.int64(11))

In [77]:
# 5. Determine the maximum value in the Series. 
np.max(sr1) , np.max(sr2)

(np.int64(9), np.int64(19))

In [31]:
a = pd.Series([1,2,3,np.nan,5,5,np.nan])
a

0    1.0
1    2.0
2    3.0
3    NaN
4    5.0
5    5.0
6    NaN
dtype: float64

In [32]:
# 6. Use the isnull() method to identify missing values. 
a.isnull()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

In [33]:
# 7. Use the notnull() method to identify non-missing values
a.notnull()

0     True
1     True
2     True
3    False
4     True
5     True
6    False
dtype: bool

In [34]:
# Working with DataFrame 
#  1. Create a 4x2 DataFrame that includes some missing values.
data =np.arange(11,19).reshape(4,2)
data

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [35]:
df = pd.DataFrame(data)
df

0   1
0  11  12
1  13  14
2  15  16
3  17  18

In [36]:
df.columns = list('ab')

In [37]:
df

a   b
0  11  12
1  13  14
2  15  16
3  17  18

In [38]:
df.iloc[1,1] = np.nan

In [39]:
df.iloc[3,0] = np.nan

In [40]:
df

a     b
0  11.0  12.0
1  13.0   NaN
2  15.0  16.0
3   NaN  18.0

In [41]:
df.drop(columns = 'a')

b
0  12.0
1   NaN
2  16.0
3  18.0

In [42]:
df['c'] = [np.nan,11,np.nan,12]

In [43]:
df

a     b     c
0  11.0  12.0   NaN
1  13.0   NaN  11.0
2  15.0  16.0   NaN
3   NaN  18.0  12.0

In [44]:
# 4. Fill missing values in columns using forward-fill. 
df.fillna(method = 'ffill',axis = 0)

C:\Users\P G Chopda\AppData\Local\Temp\ipykernel_2688\2210018539.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill',axis = 0)


a     b     c
0  11.0  12.0   NaN
1  13.0  12.0  11.0
2  15.0  16.0  11.0
3  15.0  18.0  12.0

In [26]:
# 5. Fill missing values in rows using backward-fill. 
df.fillna(method = 'bfill',axis = 0)

C:\Users\P G Chopda\AppData\Local\Temp\ipykernel_20908\677531001.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'bfill',axis = 0)


0    1    2
0  1.0  3.0  2.0
1  2.0  3.0  4.0
2  NaN  4.0  NaN

# Hierarchical Indexing

In [45]:
import numpy as np
import pandas as pd

In [56]:
index = [('California',2010),('California',2020),
        ('New York',2010),('New York',2020),
        ('Taxes',2010),('Taxes',2020)]

population = [37253956,39538223,19378102,20201249,25145561,29145505]
pop = pd.Series (population , index = index)
pop

(California, 2010)    37253956
(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Taxes, 2010)         25145561
(Taxes, 2020)         29145505
dtype: int64

In [57]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2010),
            ('California', 2020),
            (  'New York', 2010),
            (  'New York', 2020),
            (     'Taxes', 2010),
            (     'Taxes', 2020)],
           )

In [58]:
pop = pop.reindex(index)
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Taxes       2010    25145561
            2020    29145505
dtype: int64

In [59]:
pop[:,2020]

California    39538223
New York      20201249
Taxes         29145505
dtype: int64

In [60]:
# here unskack() is convert multi index data into data frame
pop_df = pop.unstack()
pop_df

2010      2020
California  37253956  39538223
New York    19378102  20201249
Taxes       25145561  29145505

In [61]:
# here stack() convert multi index data in row way
pop_df.stack()

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Taxes       2010    25145561
            2020    29145505
dtype: int64

In [62]:
pop_df = pd.DataFrame({'total':pop,'under18':[9284094,8898092,4318033,418152/8,6875123,7458964]})
pop_df

total    under18
California 2010  37253956  9284094.0
           2020  39538223  8898092.0
New York   2010  19378102  4318033.0
           2020  20201249    52269.0
Taxes      2010  25145561  6875123.0
           2020  29145505  7458964.0

In [63]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18.unstack()

2010      2020
California  0.249211  0.225050
New York    0.222831  0.002587
Taxes       0.273413  0.255922

In [64]:
df = pd.DataFrame(np.random.rand(4,2),index = [['a','a','b','b'],[1,2,1,2]],columns = ['data1','data2'])
df

data1     data2
a 1  0.644311  0.013387
  2  0.438100  0.364596
b 1  0.889343  0.401791
  2  0.721203  0.557214

In [65]:
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Taxes       2010    25145561
            2020    29145505
dtype: int64

In [66]:
pop.index.names = ['state','year']
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Taxes       2010    25145561
            2020    29145505
dtype: int64

In [67]:
# hierarchiccal indeces and columns
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],
                                  names = ['year','visit'])
columns = pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']],names = ['subject','type'])

# mock some data
data = np.round(np.random.randn(4,6),1)
data[:,::2] *= 10
data +=37

# create the data frome 
health_data = pd.DataFrame(data,index = index,columns = columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      23.0  37.5  40.0  36.2  28.0  37.8
     2      25.0  37.0  46.0  37.5  40.0  36.9
2014 1      46.0  38.3  23.0  37.6  44.0  37.4
     2      30.0  36.2  45.0  37.4  30.0  37.5

In [68]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      40.0  36.2
     2      46.0  37.5
2014 1      23.0  37.6
     2      45.0  37.4

In [69]:
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Taxes       2010    25145561
            2020    29145505
dtype: int64

In [70]:
pop['California',2010]

np.int64(37253956)

In [71]:
pop['California']

year
2010    37253956
2020    39538223
dtype: int64

In [72]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      23.0  37.5  40.0  36.2  28.0  37.8
     2      25.0  37.0  46.0  37.5  40.0  36.9
2014 1      46.0  38.3  23.0  37.6  44.0  37.4
     2      30.0  36.2  45.0  37.4  30.0  37.5

In [73]:
health_data['Guido','HR']

year  visit
2013  1        40.0
      2        46.0
2014  1        23.0
      2        45.0
Name: (Guido, HR), dtype: float64

In [75]:
health_data.iloc[:2,:2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      23.0  37.5
     2      25.0  37.0

In [76]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        23.0
      2        25.0
2014  1        46.0
      2        30.0
Name: (Bob, HR), dtype: float64

In [77]:
# if we do both sclicing like row and columns then we use IndexSlice
idx = pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      23.0  40.0  28.0
2014 1      46.0  23.0  44.0

In [78]:
help(pd.IndexSlice)

Help on _IndexSlice in module pandas.core.indexing object:

class _IndexSlice(builtins.object)
 |  Create an object to more easily perform multi-index slicing.
 |
 |  See Also
 |  --------
 |  MultiIndex.remove_unused_levels : New MultiIndex with no unused levels.
 |
 |  Notes
 |  -----
 |  See :ref:`Defined Levels <advanced.shown_levels>`
 |  for further info on slicing a MultiIndex.
 |
 |  Examples
 |  --------
 |  >>> midx = pd.MultiIndex.from_product([['A0','A1'], ['B0','B1','B2','B3']])
 |  >>> columns = ['foo', 'bar']
 |  >>> dfmi = pd.DataFrame(np.arange(16).reshape((len(midx), len(columns))),
 |  ...                     index=midx, columns=columns)
 |
 |  Using the default slice command:
 |
 |  >>> dfmi.loc[(slice(None), slice('B0', 'B1')), :]
 |             foo  bar
 |      A0 B0    0    1
 |         B1    2    3
 |      A1 B0    8    9
 |         B1   10   11
 |
 |  Using the IndexSlice class for a more intuitive command:
 |
 |  >>> idx = pd.IndexSlice
 |  >>> dfmi.loc[idx[:,

In [79]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        23.0
      2        25.0
2014  1        46.0
      2        30.0
Name: (Bob, HR), dtype: float64

In [80]:
import numpy as np
import pandas as pd

In [81]:
# sorted and unsorted indices
index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data = pd.Series(np.random.rand(6),index = index)
data.index.names = ['char','int']
data

char  int
a     1      0.960628
      2      0.968675
c     1      0.734547
      2      0.979599
b     1      0.654299
      2      0.429627
dtype: float64

In [82]:
try:
    data['a':'b']
except KeyError as e:
    print("KeyError",e)

KeyError 'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [83]:
data = data.sort_index()
data

char  int
a     1      0.960628
      2      0.968675
b     1      0.654299
      2      0.429627
c     1      0.734547
      2      0.979599
dtype: float64

In [84]:
data['a':'b']

char  int
a     1      0.960628
      2      0.968675
b     1      0.654299
      2      0.429627
dtype: float64

In [85]:
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Taxes       2010    25145561
            2020    29145505
dtype: int64

In [86]:
# level 0 means row
pop.unstack(level = 0)

state  California  New York     Taxes
year                                 
2010     37253956  19378102  25145561
2020     39538223  20201249  29145505

In [87]:
# level 1 is columns
pop.unstack(level = 1)

year            2010      2020
state                         
California  37253956  39538223
New York    19378102  20201249
Taxes       25145561  29145505

In [118]:
pop.unstack().stack()

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Taxes       2010    25145561
            2020    29145505
dtype: int64

In [88]:
pop_flat = pop.reset_index(name = 'population')
pop_flat

state  year  population
0  California  2010    37253956
1  California  2020    39538223
2    New York  2010    19378102
3    New York  2020    20201249
4       Taxes  2010    25145561
5       Taxes  2020    29145505

In [89]:
pop_flat.set_index(['state','year'])

population
state      year            
California 2010    37253956
           2020    39538223
New York   2010    19378102
           2020    20201249
Taxes      2010    25145561
           2020    29145505

In [1]:
import pandas as pd

In [10]:
dic = {'maitri':[23,34,'jiya':45,'sakshi':56}
dic

SyntaxError: ':' expected after dictionary key (15906260.py, line 1)

In [11]:
pd.DataFrame([dic])

maitri  jiya  sakshi
0  (23, 34)    45      56