In [4]:
pip install pandas


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import pandas as pd

In [6]:
s1 =  pd.Series([1,2,3,34,4])
s1

0     1
1     2
2     3
3    34
4     4
dtype: int64

In [7]:
s1[2]

np.int64(3)

In [8]:
s1.values

array([ 1,  2,  3, 34,  4])

In [9]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
import numpy as np

In [11]:
marks = np.arange(30,50,2)
marks

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [12]:
smarks = pd.Series(marks)
smarks


0    30
1    32
2    34
3    36
4    38
5    40
6    42
7    44
8    46
9    48
dtype: int64

In [13]:
s1.value_counts

<bound method IndexOpsMixin.value_counts of 0     1
1     2
2     3
3    34
4     4
dtype: int64>

In [14]:
s2 = pd.Series (index = ['x','y','z'],data = [1,2,3])
s2

x    1
y    2
z    3
dtype: int64

In [15]:
display(s2.values , s2.index , s2)

array([1, 2, 3])

Index(['x', 'y', 'z'], dtype='object')

x    1
y    2
z    3
dtype: int64

In [16]:

#here firs values is data and second values is index
s3 = pd.Series ( ['x','y','z'], [1,2,3])
s3

1    x
2    y
3    z
dtype: object

In [17]:
display(s3,s3.values,s3.index)

1    x
2    y
3    z
dtype: object

array(['x', 'y', 'z'], dtype=object)

Index([1, 2, 3], dtype='int64')

In [18]:
s3.values

array(['x', 'y', 'z'], dtype=object)

In [19]:
s3[2]

'y'

In [20]:
s3[:3]

1    x
2    y
3    z
dtype: object

In [21]:
s3[1:3]

2    y
3    z
dtype: object

In [22]:
dic = {"Maitri" : "A" , "Jiya" : "A+" , "Sakshi" : "A"}
dic

{'Maitri': 'A', 'Jiya': 'A+', 'Sakshi': 'A'}

In [23]:
pd.Series(dic)

Maitri     A
Jiya      A+
Sakshi     A
dtype: object

In [24]:
data = ['A+','A++','A']
ind = ['Maitri','jiya','sakshi']
pd.Series(data,ind)

Maitri     A+
jiya      A++
sakshi      A
dtype: object

In [25]:
pd.Series(ind,data)

A+     Maitri
A++      jiya
A      sakshi
dtype: object

In [26]:
display(pd.Series(ind,data).index)

Index(['A+', 'A++', 'A'], dtype='object')

In [27]:
display(pd.Series(ind,data).values)

array(['Maitri', 'jiya', 'sakshi'], dtype=object)

In [29]:
tup = ('t','u','p','l','e')
tup

('t', 'u', 'p', 'l', 'e')

In [30]:
pd.Series(tup)

0    t
1    u
2    p
3    l
4    e
dtype: object

In [33]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [35]:
pd.DataFrame({'riya':[50,53],'sia' : [1,2]})

riya  sia
0    50    1
1    53    2

In [40]:
pd.DataFrame({'riya':[50,53],'sia' : [1,2]}, index= ["Python","Fds"])

riya  sia
Python    50    1
Fds       53    2

In [43]:
pd.DataFrame([[24,23],[45,56]],columns = ['A','B'], index = ['Py','Ds'])

A   B
Py  24  23
Ds  45  56

In [44]:
import numpy as np

In [49]:
np.random.seed(9)
marks = pd.DataFrame(np.random.randint(0,30,(3,3)),index = ['Maitri','Jiya','Sakshi'],columns = ['Py','Fds','Cai'])
marks

Py  Fds  Cai
Maitri  28   21   22
Jiya    24   27   22
Sakshi  29    1   22

In [50]:
marks.columns

Index(['Py', 'Fds', 'Cai'], dtype='object')

In [51]:
marks.values

array([[28, 21, 22],
       [24, 27, 22],
       [29,  1, 22]], dtype=int32)

In [52]:
marks.index

Index(['Maitri', 'Jiya', 'Sakshi'], dtype='object')

In [53]:
marks['Py']

Maitri    28
Jiya      24
Sakshi    29
Name: Py, dtype: int32

In [54]:
marks['Fds']

Maitri    21
Jiya      27
Sakshi     1
Name: Fds, dtype: int32

In [56]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
pd.DataFrame(a,index = [1,2,3,4,5],columns = ['a','b','c','d','e'])

a   b   c   d   e
1   0   1   2   3   4
2   5   6   7   8   9
3  10  11  12  13  14
4  15  16  17  18  19
5  20  21  22  23  24

In [58]:
marks['total'] = marks['Py']+marks['Fds']+marks['Cai']
marks

Py  Fds  Cai  total
Maitri  28   21   22     71
Jiya    24   27   22     73
Sakshi  29    1   22     52

In [63]:
marks['percentage'] = marks['total'] / 100
marks

Py  Fds  Cai  total  persontage  percentage
Maitri  28   21   22     71        0.71        0.71
Jiya    24   27   22     73        0.73        0.73
Sakshi  29    1   22     52        0.52        0.52

In [68]:
# indexing & selection

marks[['Py' , 'Fds']]

Py  Fds
Maitri  28   21
Jiya    24   27
Sakshi  29    1

# we have three function in indexing and selection 
dataframe_name.loc
---> in loc we  put lable
dataframe_name.iloc
---> in iloc we put index no / numeric

dataframe_name.ix
---> in ix we put both 


In [76]:
#pd.DataFrame.loc?

In [75]:
#pd.DataFrame.iloc?

In [78]:
marks.loc['Jiya']

Py            24.00
Fds           27.00
Cai           22.00
total         73.00
persontage     0.73
percentage     0.73
Name: Jiya, dtype: float64

In [83]:
marks.loc['Jiya','Py']

np.int32(24)

In [86]:
marks.loc['Jiya','Py':'Cai']

Py     24.0
Fds    27.0
Cai    22.0
Name: Jiya, dtype: float64

In [87]:
marks.loc[:'Maitri',['Py','Fds']]

Py  Fds
Maitri  28   21

In [89]:
marks.loc[:'Maitri','Py':]


Py  Fds  Cai  total  persontage  percentage
Maitri  28   21   22     71        0.71        0.71

In [92]:
marks.loc['Jiya','Py':'Cai']

Py     24.0
Fds    27.0
Cai    22.0
Name: Jiya, dtype: float64

In [94]:
marks.iloc[:2]

Py  Fds  Cai  total  persontage  percentage
Maitri  28   21   22     71        0.71        0.71
Jiya    24   27   22     73        0.73        0.73

In [96]:
marks.iloc[:2,1:3]

Fds  Cai
Maitri   21   22
Jiya     27   22

In [97]:
marks.iloc[:2,0:3]

Py  Fds  Cai
Maitri  28   21   22
Jiya    24   27   22

In [98]:
marks.iloc[:,3]

Maitri    71
Jiya      73
Sakshi    52
Name: total, dtype: int32

In [103]:
marks.iloc[:,3]>16


Maitri    True
Jiya      True
Sakshi    True
Name: total, dtype: bool

In [104]:
marks[marks.Py>25]   # first method

Py  Fds  Cai  total  persontage  percentage
Maitri  28   21   22     71        0.71        0.71
Sakshi  29    1   22     52        0.52        0.52

In [106]:
marks[marks['Py']>25]  #second methon

Py  Fds  Cai  total  persontage  percentage
Maitri  28   21   22     71        0.71        0.71
Sakshi  29    1   22     52        0.52        0.52