In [4]:
#pip install pandas

In [5]:
import pandas as pd

In [6]:
s1 =  pd.Series([1,2,3,34,4])
s1

0     1
1     2
2     3
3    34
4     4
dtype: int64

In [7]:
s1[2]

np.int64(3)

In [8]:
s1.values

array([ 1,  2,  3, 34,  4])

In [9]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
import numpy as np

In [11]:
marks = np.arange(30,50,2)
marks

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [12]:
smarks = pd.Series(marks)
smarks


0    30
1    32
2    34
3    36
4    38
5    40
6    42
7    44
8    46
9    48
dtype: int64

In [13]:
s1.value_counts

<bound method IndexOpsMixin.value_counts of 0     1
1     2
2     3
3    34
4     4
dtype: int64>

In [14]:
s2 = pd.Series (index = ['x','y','z'],data = [1,2,3])
s2

x    1
y    2
z    3
dtype: int64

In [15]:
display(s2.values , s2.index , s2)

array([1, 2, 3])

Index(['x', 'y', 'z'], dtype='object')

x    1
y    2
z    3
dtype: int64

In [16]:

#here firs values is data and second values is index
s3 = pd.Series ( ['x','y','z'], [1,2,3])
s3

1    x
2    y
3    z
dtype: object

In [17]:
display(s3,s3.values,s3.index)

1    x
2    y
3    z
dtype: object

array(['x', 'y', 'z'], dtype=object)

Index([1, 2, 3], dtype='int64')

In [18]:
s3.values

array(['x', 'y', 'z'], dtype=object)

In [19]:
s3[2]

'y'

In [20]:
s3[:3]

1    x
2    y
3    z
dtype: object

In [21]:
s3[1:3]

2    y
3    z
dtype: object

In [22]:
dic = {"Maitri" : "A" , "Jiya" : "A+" , "Sakshi" : "A"}
dic

{'Maitri': 'A', 'Jiya': 'A+', 'Sakshi': 'A'}

In [23]:
pd.Series(dic)

Maitri     A
Jiya      A+
Sakshi     A
dtype: object

In [24]:
data = ['A+','A++','A']
ind = ['Maitri','jiya','sakshi']
pd.Series(data,ind)

Maitri     A+
jiya      A++
sakshi      A
dtype: object

In [25]:
pd.Series(ind,data)

A+     Maitri
A++      jiya
A      sakshi
dtype: object

In [26]:
display(pd.Series(ind,data).index)

Index(['A+', 'A++', 'A'], dtype='object')

In [27]:
display(pd.Series(ind,data).values)

array(['Maitri', 'jiya', 'sakshi'], dtype=object)

In [28]:
tup = ('t','u','p','l','e')
tup

('t', 'u', 'p', 'l', 'e')

In [29]:
pd.Series(tup)

0    t
1    u
2    p
3    l
4    e
dtype: object

In [30]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:     
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows 

In [31]:
pd.DataFrame({'riya':[50,53],'sia' : [1,2]})

riya  sia
0    50    1
1    53    2

In [30]:
pd.DataFrame({'riya':[50,53],'sia' : [1,2]}, index= ["Python","Fds"])

riya  sia
Python    50    1
Fds       53    2

In [47]:
pd.DataFrame([[24,23],[45,56]],columns = ['A','B'], index = ['Py','Ds'])

A   B
Py  24  23
Ds  45  56

In [48]:
import numpy as np

In [53]:
np.random.seed(9)
marks = pd.DataFrame(np.random.randint(0,30,(3,3)),index = ['Maitri','Jiya','Sakshi'],columns = ['Py','Fds','Cai'])
marks

Py  Fds  Cai
Maitri  28   21   22
Jiya    24   27   22
Sakshi  29    1   22

In [54]:
marks.columns

Index(['Py', 'Fds', 'Cai'], dtype='object')

In [55]:
marks.values

array([[28, 21, 22],
       [24, 27, 22],
       [29,  1, 22]], dtype=int32)

In [56]:
marks.index

Index(['Maitri', 'Jiya', 'Sakshi'], dtype='object')

In [57]:
marks['Py']

Maitri    28
Jiya      24
Sakshi    29
Name: Py, dtype: int32

In [58]:
marks['Fds']

Maitri    21
Jiya      27
Sakshi     1
Name: Fds, dtype: int32

In [59]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [60]:
pd.DataFrame(a,index = [1,2,3,4,5],columns = ['a','b','c','d','e'])

a   b   c   d   e
1   0   1   2   3   4
2   5   6   7   8   9
3  10  11  12  13  14
4  15  16  17  18  19
5  20  21  22  23  24

In [61]:
marks['total'] = marks['Py']+marks['Fds']+marks['Cai']
marks

Py  Fds  Cai  total
Maitri  28   21   22     71
Jiya    24   27   22     73
Sakshi  29    1   22     52

In [62]:
marks['percentage'] = marks['total'] / 100
marks

Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71
Jiya    24   27   22     73        0.73
Sakshi  29    1   22     52        0.52

In [63]:
# indexing & selection

marks[['Py' , 'Fds']]

Py  Fds
Maitri  28   21
Jiya    24   27
Sakshi  29    1

# we have three function in indexing and selection 
dataframe_name.loc
---> in loc we  put lable
  dataframe_name.iloc
---> in iloc we put index no / numeric

dataframe_name.ix
---> in ix we put both 


In [64]:
#pd.DataFrame.loc?

In [65]:
#pd.DataFrame.iloc?

In [66]:
marks.loc['Jiya']

Py            24.00
Fds           27.00
Cai           22.00
total         73.00
percentage     0.73
Name: Jiya, dtype: float64

In [67]:
marks.loc['Jiya','Py']

np.int32(24)

In [68]:
marks.loc['Jiya','Py':'Cai']

Py     24.0
Fds    27.0
Cai    22.0
Name: Jiya, dtype: float64

In [69]:
marks.loc[:'Maitri',['Py','Fds']]

Py  Fds
Maitri  28   21

In [70]:
marks.loc[:'Maitri','Py':]


Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71

In [71]:
marks.loc['Jiya','Py':'Cai']

Py     24.0
Fds    27.0
Cai    22.0
Name: Jiya, dtype: float64

In [72]:
marks.iloc[:2]

Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71
Jiya    24   27   22     73        0.73

In [73]:
marks.iloc[:2,1:3]

Fds  Cai
Maitri   21   22
Jiya     27   22

In [74]:
marks.iloc[:2,0:3]

Py  Fds  Cai
Maitri  28   21   22
Jiya    24   27   22

In [75]:
marks.iloc[:,3]

Maitri    71
Jiya      73
Sakshi    52
Name: total, dtype: int32

In [76]:
marks.iloc[:,3]>16


Maitri    True
Jiya      True
Sakshi    True
Name: total, dtype: bool

In [57]:
marks[marks.Py>25]   # first method

Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71
Sakshi  29    1   22     52        0.52

In [58]:
marks[marks['Py']>25]  #second methon

Py  Fds  Cai  total  percentage
Maitri  28   21   22     71        0.71
Sakshi  29    1   22     52        0.52

# Assignment Excise 

In [59]:
import pandas as pd

In [60]:
import numpy as np

In [71]:
#Q. 1
prod = ['ALOE BARRY NECTOR' , 'FOREVER GEL' , 'ALOE PEACHES','ALOE MANGO']
prid = ['FL01','FL02','FL03','FL04']
price = [1000,1100,1120,1130] 
c = np.array(price)
c


array([1000, 1100, 1120, 1130])

In [72]:
product = pd.DataFrame(prod, prid,columns = ['Product name'])
product
product['price'] = price
product

Product name  price
FL01  ALOE BARRY NECTOR   1000
FL02        FOREVER GEL   1100
FL03       ALOE PEACHES   1120
FL04         ALOE MANGO   1130

In [85]:
# q.2 
product['Product name']

FL01    ALOE BARRY NECTOR
FL02          FOREVER GEL
FL03         ALOE PEACHES
FL04           ALOE MANGO
Name: Product name, dtype: object

In [86]:
# q. 7
product.loc["FL01" : "FL03"]

Product name  price
FL01  ALOE BARRY NECTOR   1000
FL02        FOREVER GEL   1100
FL03       ALOE PEACHES   1120

In [95]:
# q.8
product.iloc[2,1]

np.int64(1120)

In [96]:
# q. 9
product.iloc[2:,1]

FL03    1120
FL04    1130
Name: price, dtype: int64

In [98]:
# q. 10
product.iloc[:,0]

FL01    ALOE BARRY NECTOR
FL02          FOREVER GEL
FL03         ALOE PEACHES
FL04           ALOE MANGO
Name: Product name, dtype: object

In [63]:
# q.10

np.random.seed(15)
mark = pd.DataFrame(np.random.randint(0,50,(5,3)),index = ['Maitri','Jiya','Sakshi','Jonty','Man'],columns = ['Py','Fds','Cai'])
mark

Py  Fds  Cai
Maitri   8   12    5
Jiya     0   28   27
Sakshi   7   11   21
Jonty   47   29   17
Man     45   31   23

In [64]:
#11
mark[mark['Py']<20 ] = 21


In [65]:
mark

Py  Fds  Cai
Maitri  21   21   21
Jiya    21   21   21
Sakshi  21   21   21
Jonty   47   29   17
Man     45   31   23

In [66]:
# 12
mark+2

Py  Fds  Cai
Maitri  23   23   23
Jiya    23   23   23
Sakshi  23   23   23
Jonty   49   31   19
Man     47   33   25

In [67]:
#q. 13
mark[mark['Py']>30 ]

Py  Fds  Cai
Jonty  47   29   17
Man    45   31   23

In [68]:
#q.13
mark[mark['Fds']>30 ]

Py  Fds  Cai
Man  45   31   23

In [69]:
#q. 14
mark['per'] = (mark['Py']+mark['Fds']+mark['Cai']) / 100
mark['per']

Maitri    0.63
Jiya      0.63
Sakshi    0.63
Jonty     0.93
Man       0.99
Name: per, dtype: float64

In [70]:
mark['per']

Maitri    0.63
Jiya      0.63
Sakshi    0.63
Jonty     0.93
Man       0.99
Name: per, dtype: float64

In [9]:
import pandas as pd
import numpy as np

In [12]:
rng = np.random.RandomState(42)

In [13]:
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [16]:
df = pd.DataFrame(rng.randint(0,10,(3,4)),columns = ['A','B','C','D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [17]:
# exponencial funciton
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [18]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [19]:
area = pd.Series({'Uttar Pradesh':243268,'Maharashtra' : 307713,'Bihar':94163},name = "area")
area

Uttar Pradesh    243268
Maharashtra      307713
Bihar             94163
Name: area, dtype: int64

In [31]:
population =  pd.Series({'West Bengal':91276115,'Maharashtra':124484447,'Bihar':104099452},name = "population")
population

West Bengal     91276115
Maharashtra    124484447
Bihar          104099452
Name: population, dtype: int64

In [32]:
population_density = population / area
population_density

Bihar            1105.523953
Maharashtra       404.547247
Uttar Pradesh            NaN
West Bengal              NaN
dtype: float64

In [34]:
A = pd.Series([2,4,6],index = [0,1,2])
B = pd.Series([1,3,5],index = [1,2,3])

In [35]:
A+B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [36]:
A.add(B,fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [37]:
A = pd.DataFrame(rng.randint(0,15,(2,2)),columns = list('AB'))
B = pd.DataFrame(rng.randint(0,10,(3,3)),columns = list('BAC'))

In [38]:
A + B

A     B   C
0   2.0  12.0 NaN
1  20.0  13.0 NaN
2   NaN   NaN NaN

In [39]:
fill = A.stack().mean() # converts df A into a series with all values stacked vertically calculates the mean


In [40]:
A.add(B,fill_value = fill)

A     B     C
0   2.0  12.0  12.0
1  20.0  13.0  13.0
2   8.0  16.0  17.0

In [45]:
A = np.random.randint(10,size = (3,4))
A

array([[1, 5, 1, 9],
       [6, 4, 6, 5],
       [7, 4, 6, 5]], dtype=int32)

In [46]:
# thsi is subtract only row wise 
A - A[0]

array([[ 0,  0,  0,  0],
       [ 5, -1,  5, -4],
       [ 6, -1,  5, -4]], dtype=int32)

In [49]:
df = pd.DataFrame(A,columns = list('QRST'))
df

Q  R  S  T
0  1  5  1  9
1  6  4  6  5
2  7  4  6  5

In [50]:
df - df.iloc[0] # subtraction is applied row wise by default 

Q  R  S  T
0  0  0  0  0
1  5 -1  5 -4
2  6 -1  5 -4

In [51]:
df.subtract(df['R'],axis = 0) # column wise operations, we can use axis keyword

Q  R  S  T
0 -4  0 -4  4
1  2  0  2  1
2  3  0  2  1

In [56]:
halfrow = df.iloc[0,::2] #select every other element from first row i.e. Q and S from 1st row 
halfrow

Q    1
S    1
Name: 0, dtype: int32

In [57]:
df - halfrow # operation - subtraction

Q   R    S   T
0  0.0 NaN  0.0 NaN
1  5.0 NaN  5.0 NaN
2  6.0 NaN  5.0 NaN

## pandas Practice

In [4]:
import pandas as pd

In [5]:
# q.1
lst = [10,20,30,40]
lst

[10, 20, 30, 40]

In [7]:
l = pd.Series(lst)
l

0    10
1    20
2    30
3    40
dtype: int64

In [8]:
# q.2
l[2]

np.int64(30)

In [9]:
# q.3
l[0:3]

0    10
1    20
2    30
dtype: int64

In [11]:
# q.4
l.index = ["a","b","c","d"]
l

a    10
b    20
c    30
d    40
dtype: int64

In [13]:
# q.5
l["b"] =50
l

a    10
b    50
c    30
d    40
dtype: int64

In [14]:
# q.6 
dic = {'Delhi': 1, 'Jaipur': 2,'Chennai': 3, 'Surat': 4, 'Agra': 5}
dic

{'Delhi': 1, 'Jaipur': 2, 'Chennai': 3, 'Surat': 4, 'Agra': 5}

In [16]:
d = pd.Series(dic)
d

Delhi      1
Jaipur     2
Chennai    3
Surat      4
Agra       5
dtype: int64

In [24]:
# q.7
d["Delhi"]

np.int64(1)

In [25]:
d[1:4]

Jaipur     2
Chennai    3
Surat      4
dtype: int64

In [26]:
# q.8
import numpy as np

In [30]:
dt = np.arange(0,4).reshape(2,2)
dt

array([[0, 1],
       [2, 3]])

In [69]:
df = pd.DataFrame(dt,columns = ['a','b'])
df

a  b
0  0  1
1  2  3

In [70]:
# q.9
df[1:]

a  b
1  2  3

In [71]:
# 10
f = [[3,4]]
f

[[3, 4]]

In [87]:
df['c'] = [4,5]

In [88]:
df

a  b  (c, d)  c
0  0  1       4  4
1  2  3       5  5

In [90]:
df["c"]

0    4
1    5
Name: c, dtype: int64

In [100]:
c = df.drop(columns = "b")

In [101]:
c

a  (c, d)  c
0  0       4  4
1  2       5  5